version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  # docker run -p 8000:8000 -p 4318:4318 -p 4317:4317 -p 8080:8080 -p 8002:8002 hyperdx/hyperdx-local
  hyperdx:
    image: hyperdx/hyperdx-local
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8000:8000"
      - "8002:8002"
      - "4318:4318"
      - "4317:4317"
